### ISSUE TITLE
trouble downloading javautil from http://maven.clapper.org/ thru maven 3.2.5 clean install

### ISSUE THREAD

**Issue by draycasejr** [bmc/javautil#14]
in my project I try to do a 'mvn clean install' with javautil 3.1.1 as a dependency. 
I get the following and it fails.  I am trying to figure it out myself currently.
It also failed with maven 3.0.7?
It could be a cert problem, based on the final output, but it sure looks like the URI is wrong.

<pre>Downloading: http://maven.clapper.org/javax/mail/mail/1.4.4%20(compile)/mail-1.4.4%20(compile).pom
Downloading: https://repo.maven.apache.org/maven2/javax/mail/mail/1.4.4%20(compile)/mail-1.4.4%20(compile).pom
Downloading: http://maven.clapper.org/asm/asm/3.3.1%20(compile)/asm-3.3.1%20(compile).pom
Downloading: https://repo.maven.apache.org/maven2/asm/asm/3.3.1%20(compile)/asm-3.3.1%20(compile).pom
Downloading: http://maven.clapper.org/asm/asm-commons/3.3.1%20(compile)/asm-commons-3.3.1%20(compile).pom
Downloading: https://repo.maven.apache.org/maven2/asm/asm-commons/3.3.1%20(compile)/asm-commons-3.3.1%20(compile).pom
Downloading: http://maven.clapper.org/asm/asm-tree/3.3.1%20(compile)/asm-tree-3.3.1%20(compile).pom
Downloading: https://repo.maven.apache.org/maven2/asm/asm-tree/3.3.1%20(compile)/asm-tree-3.3.1%20(compile).pom
Downloading: http://maven.clapper.org/commons-logging/commons-logging/1.1.1%20(compile)/commons-logging-1.1.1%20(compile).pom
Downloading: https://repo.maven.apache.org/maven2/commons-logging/commons-logging/1.1.1%20(compile)/commons-logging-1.1.1%20(compile).pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.676 s
[INFO] Finished at: 2015-01-22T19:35:37+00:00
[INFO] Final Memory: 4M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project knunk-core: Could not resolve dependencies for project com.knunk:knunk-core:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at org.clapper:javautil:jar:3.1.1 -> javax.mail:mail:jar:1.4.4 (compile): Failed to read artifact descriptor for javax.mail:mail:jar:1.4.4 (compile): Could not transfer artifact javax.mail:mail:pom:1.4.4 (compile) from/to central (https://repo.maven.apache.org/maven2): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
</pre>

**Comment by leon90dm** [comment]
actually it's not in maven repository

**Comment by bmc** [comment]
Fixed now. Version 3.2.0 is currently in https://dl.bintray.com/bmc/maven. I've requested that it be included in JCenter. Once it's in JCenter, I'll push it to Maven Central. In the meantime, if you add my Bintray repo, you can resolve it.
