### ISSUE TITLE
Is javautil really deployed to JCenter and Maven Central?

### ISSUE THREAD

**Issue by victornoel** [bmc/javautil#16]
Hi,

According to http://software.clapper.org/javautil/, javautil is meant to be deployed to JCentral but if I look at http://jcenter.bintray.com/org/clapper/ I can see it is not there.

So it is not deployed to Maven Central either, that's a shame :)

Thanks!

**Comment by bmc** [comment]
Fixed now. Version 3.2.0 is currently in https://dl.bintray.com/bmc/maven. I've requested that it be included in JCenter. Once it's in JCenter, I'll push it to Maven Central. In the meantime, if you add my Bintray repo, you can resolve it.

**Comment by victornoel** [comment]
@bmc great, thanks :)

**Comment by victornoel** [comment]
(it's in jcenter already btw!)
